#!/usr/bin/env node
/**
 * Compile the publisher's public key into the client (B1).
 *
 * Writes desktop-pro/embedded-key.cjs — the ONLY key source the packaged
 * updater trusts. Fail-closed policy lives in updater.cjs: when running
 * packaged (or whenever DSH_PRO_DEV_KEYS is unset), a missing embedded key
 * is a hard error, never a filesystem fallback — an attacker with disk write
 * access must not be able to swap the trust anchor.
 *
 * Usage: node infra/embed-key.mjs
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs'
import { join, resolve } from 'node:path'

const root = resolve(import.meta.dirname, '..')
const source = join(root, 'infra', 'keys', 'public.pem')
const target = join(root, 'embedded-key.cjs')

if (!existsSync(source)) throw new Error(`no public key at ${source}; run: node infra/keys.mjs generate`)
const pem = readFileSync(source, 'utf8').trim()
writeFileSync(target, `// GENERATED by infra/embed-key.mjs — the update trust anchor. Committing is fine (public).\nmodule.exports = { PUBLIC_KEY: ${JSON.stringify(`${pem}\n`)} }\n`)
console.log(`embedded-key.cjs written (${pem.split('\n').length} lines)`)
