// GENERATED by infra/embed-key.mjs — the update trust anchor. Committing is fine (public).
module.exports = { PUBLIC_KEY: "-----BEGIN PUBLIC KEY-----\nMCowBQYDK2VwAyEAAsSBEDLmML4mWJVtWuu8tR0qPO00gt4FIEWoQM9Zghw=\n-----END PUBLIC KEY-----\n" }
